### ISSUE TITLE
Can't fetch the checkpoints of the model & the link of the data (drive ) is not working

### ISSUE THREAD

**Issue by OmarMohammed88** [jianfa/RecipeSnap-a-lightweight-image-to-recipe-model#1]
hello there , 
it seems that the link of the data is not working anymore , would you update the link of the data ,
second I am trying to test the model but I cant fetch the checkpoints and got this error 
```
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```
I was trying to fetch the checkpoints using following command 
``` 
!git lfs fetch -I args.pkl 
```

**Comment by jianfa** [comment]
Github set a monthly traffic quota to free users. I uploaded the code to Google Cloud. Try this link: https://drive.google.com/drive/folders/1BsQ90gxRXkNEL936P5lpSlvU2FGy3dcN?usp=sharing

**Comment by OmarMohammed88** [comment]
thanks for the quick response. appreciate it
