### ISSUE TITLE
Download dataset

### ISSUE THREAD

**Issue by OmarMohammed88** [jianfa/RecipeSnap-a-lightweight-image-to-recipe-model#2]
hi three, 
i was trying to download the dataset (pckl) files from the URLs you attached but it seems that the links are invalid.

**Comment by OmarMohammed88** [comment]
any updates?

**Comment by jianfa** [comment]
Check this answer: https://github.com/jianfa/RecipeSnap-a-lightweight-image-to-recipe-model/issues/1#issuecomment-1427085275

**Comment by OmarMohammed88** [comment]
iam trying to train the model again not using the existing checkpoints, so I was wondering where can I find the train.pkl
and all the necessary files to be able to train the model?
thanks in advance

**Comment by jianfa** [comment]
I saved train.pk in Google Cloud. Unfortunately, it was removed after I canceled the subscription. You can train from the start by downloading the training data and snapshot from https://github.com/amzn/image-to-recipe-transformers.
